In [2]:
import random
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.cluster import KMeans
from sklearn import datasets
import sys
from tensorflow import keras

def initialize(data, k):
    centroids = []
    centroids.append(data[np.random.randint(
            data.shape[0]), :])
  
   
    for c_id in range(k - 1):
          
        dist = []
        for i in range(data.shape[0]):
            point = data[i, :]
            d = sys.maxsize
              
            for j in range(len(centroids)):
                temp_dist = (((point-centroids[j])**2).sum())**0.5
                d = min(d, temp_dist)
            dist.append(d)
              
        dist = np.array(dist)
        next_centroid = data[np.argmax(dist), :]
        centroids.append(next_centroid)
        dist = []
       
    return centroids
def kmeans(dataset, k):
    #kemans++
    centroids =initialize(dataset, k)
    dic_centroids={}
    dic_centroids_old={}
    for i in range(0,k):
        dic_centroids[i]=[]
        dic_centroids_old[i]=[]
    convergio=False
    iteracion = 1
    while not convergio:
        #print("Iteracion:",iteracion)
        iteracion+=1
        classes=[]
        for i in range(0,len(dataset)):
            min_dist = np.inf
            c = -1
            for j in range(0,k):
                
                temp_dist=(((np.array(dataset[i])-np.array(centroids[j]))**2).sum())**0.5
                
                if temp_dist < min_dist:
                    c=j
                    min_dist=temp_dist
            classes.append(c)
            dic_centroids[c].append(dataset[i])
        
        iguales = True
        for i in range(0,k):
            temp = [sum(x)/len(x) for x in zip(*dic_centroids[i])]
            fin = True
            for j in range(0,len(temp)):
                if(temp[j]!=centroids[i][j]):
                    fin=False
            if not fin: 
                centroids[i]=temp
                iguales=False
            
            dic_centroids[i]=[]
        convergio=iguales   
       
       
    return centroids,classes





/home/nicolas/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/nicolas/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/nicolas/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/nicolas/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:5

In [3]:

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()



In [4]:
X = x_train.reshape(len(x_train),-1)
Y = y_train


X = X.astype(float) / 255.
print(X)
centroids, classes = kmeans(X,36)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


KeyboardInterrupt: 

In [ ]:
fig, axs = plt.subplots(1, 36, figsize = (12, 12))
plt.gray()

for i, ax in enumerate(axs.flat):
  ax.matshow(np.array(centroids[i]).reshape(28, 28))

fig.show()